service: vrc9xx-multimatic-bridge

app: nodejs-multimatic
org: samover

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpackIncludeModules: true

functions:
  authFn:
    handler: src/auth-fn.handler
  hello:
    handler: src/function1.handler
    events:
      - http:
          path: hello
          authorizer: auth
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
