service: vrc9xx-multimatic-bridge

app: nodejs-multimatic
org: samover

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpackIncludeModules: true

functions:
  authorizerFn:
    handler: src/cognitoAuthorizerFn.handler
  profileFn:
    handler: src/profileFn.handler
    events:
      - http:
          path: profile/edit
          method: get
