name: Build

on:
  push:
    branches: [ develop, master ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set deployment environment
      id: environment
      run: |
        if '${{ endsWith(github.ref, '/master') }}' == 'true'; then echo ::set-output name=env::"prod";else echo ::set-output name=env::"dev"; fi

    - name: Install dependencies
      run: npm install

    - name: Deploy Backend
      uses: serverless/github-action@v1.53.0
      with:
        args: deploy --stage ${{ steps.environment.outputs.env }} --nos3sync

    - name: Build Client
      uses: serverless/github-action@v1.53.0
      with:
        args: client build --stage ${{ steps.environment.outputs.env }}

    - name: Upload client
      uses: serverless/github-action@v1.53.0
      with:
        args: s3sync --stage ${{ steps.environment.outputs.env }}

