name: Serverless Deploy

on:
  push:
    branches: [ develop, master ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Deploy Develop
      if: github.ref == 'refs/heads/develop'
      uses: serverless/github-action@v1.53.0
      with:
        args: deploy --stage dev

    - name: Deploy Master
      if: github.ref == 'refs/heads/master'
      uses: serverless/github-action@v1.53.0
      with:
        args: deploy --stage prod
